export default {
  "audit-documents": "Audit Documents",
  "aws-sigv4": "AWS Signature V4",
  "block-field-suggestions": "Block Field Suggestions",
  "character-limit": "Character Limit",
  cors: "CORS",
  "csrf-prevention": "CSRF Prevention",
  "demand-control": "Demand Control",
  "disable-introspection": "Disable Introspection",
  "hmac-signature": "HMAC Signature",
  https: "HTTPS",
  index: "Overview",
  "max-aliases": "Max Aliases",
  "max-depth": "Max Depth",
  "max-directives": "Max Directives",
  "max-tokens": "Max Tokens",
  "rate-limiting": "Rate Limiting",
};
