export default {
  "apollo-gateway": "Apollo Gateway",
  "apollo-router": "Apollo Router",
  "apollo-server": "Apollo Server",
  "ci-cd": "CI/CD Guide",
  "code-first": "Code-First Frameworks",
  envelop: "Envelop",
  "gqlgen-go": "GQLGen (GoLang)",
  "grafbase-gateway": "Grafbase Gateway",
  "graphql-code-generator": "GraphQL Code Generator",
  "graphql-ruby": "GraphQL Ruby",
  "graphql-yoga": "GraphQL Yoga",
  index: "Introduction",
  lighthouse: "Lighthouse (Laravel)",
  "schema-stitching": "Schema Stitching",
};
