/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as LandingRouteImport } from './routes/_landing'
import { Route as LandingIndexRouteImport } from './routes/_landing/index'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as LandingPricingRouteImport } from './routes/_landing/pricing'
import { Route as LandingPartnersRouteImport } from './routes/_landing/partners'
import { Route as LandingOssFriendsRouteImport } from './routes/_landing/oss-friends'
import { Route as LandingGatewayRouteImport } from './routes/_landing/gateway'
import { Route as LandingEcosystemRouteImport } from './routes/_landing/ecosystem'
import { Route as LandingCaseStudiesRouteImport } from './routes/_landing/case-studies'
import { Route as LandingFederationIndexRouteImport } from './routes/_landing/federation/index'
import { Route as LlmsDotmdxDocsSplatRouteImport } from './routes/llms[.]mdx.docs.$'

const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/_landing',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingRoute,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingPricingRoute = LandingPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => LandingRoute,
} as any)
const LandingPartnersRoute = LandingPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => LandingRoute,
} as any)
const LandingOssFriendsRoute = LandingOssFriendsRouteImport.update({
  id: '/oss-friends',
  path: '/oss-friends',
  getParentRoute: () => LandingRoute,
} as any)
const LandingGatewayRoute = LandingGatewayRouteImport.update({
  id: '/gateway',
  path: '/gateway',
  getParentRoute: () => LandingRoute,
} as any)
const LandingEcosystemRoute = LandingEcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => LandingRoute,
} as any)
const LandingCaseStudiesRoute = LandingCaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => LandingRoute,
} as any)
const LandingFederationIndexRoute = LandingFederationIndexRouteImport.update({
  id: '/federation/',
  path: '/federation/',
  getParentRoute: () => LandingRoute,
} as any)
const LlmsDotmdxDocsSplatRoute = LlmsDotmdxDocsSplatRouteImport.update({
  id: '/llms.mdx/docs/$',
  path: '/llms.mdx/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/case-studies': typeof LandingCaseStudiesRoute
  '/ecosystem': typeof LandingEcosystemRoute
  '/gateway': typeof LandingGatewayRoute
  '/oss-friends': typeof LandingOssFriendsRoute
  '/partners': typeof LandingPartnersRoute
  '/pricing': typeof LandingPricingRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/': typeof LandingIndexRoute
  '/llms.mdx/docs/$': typeof LlmsDotmdxDocsSplatRoute
  '/federation': typeof LandingFederationIndexRoute
}
export interface FileRoutesByTo {
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/case-studies': typeof LandingCaseStudiesRoute
  '/ecosystem': typeof LandingEcosystemRoute
  '/gateway': typeof LandingGatewayRoute
  '/oss-friends': typeof LandingOssFriendsRoute
  '/partners': typeof LandingPartnersRoute
  '/pricing': typeof LandingPricingRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/': typeof LandingIndexRoute
  '/llms.mdx/docs/$': typeof LlmsDotmdxDocsSplatRoute
  '/federation': typeof LandingFederationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_landing': typeof LandingRouteWithChildren
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/_landing/case-studies': typeof LandingCaseStudiesRoute
  '/_landing/ecosystem': typeof LandingEcosystemRoute
  '/_landing/gateway': typeof LandingGatewayRoute
  '/_landing/oss-friends': typeof LandingOssFriendsRoute
  '/_landing/partners': typeof LandingPartnersRoute
  '/_landing/pricing': typeof LandingPricingRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/_landing/': typeof LandingIndexRoute
  '/llms.mdx/docs/$': typeof LlmsDotmdxDocsSplatRoute
  '/_landing/federation/': typeof LandingFederationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/llms-full.txt'
    | '/llms.txt'
    | '/case-studies'
    | '/ecosystem'
    | '/gateway'
    | '/oss-friends'
    | '/partners'
    | '/pricing'
    | '/api/search'
    | '/docs/$'
    | '/'
    | '/llms.mdx/docs/$'
    | '/federation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/llms-full.txt'
    | '/llms.txt'
    | '/case-studies'
    | '/ecosystem'
    | '/gateway'
    | '/oss-friends'
    | '/partners'
    | '/pricing'
    | '/api/search'
    | '/docs/$'
    | '/'
    | '/llms.mdx/docs/$'
    | '/federation'
  id:
    | '__root__'
    | '/_landing'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/_landing/case-studies'
    | '/_landing/ecosystem'
    | '/_landing/gateway'
    | '/_landing/oss-friends'
    | '/_landing/partners'
    | '/_landing/pricing'
    | '/api/search'
    | '/docs/$'
    | '/_landing/'
    | '/llms.mdx/docs/$'
    | '/_landing/federation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LandingRoute: typeof LandingRouteWithChildren
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  ApiSearchRoute: typeof ApiSearchRoute
  DocsSplatRoute: typeof DocsSplatRoute
  LlmsDotmdxDocsSplatRoute: typeof LlmsDotmdxDocsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/': {
      id: '/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/pricing': {
      id: '/_landing/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof LandingPricingRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/partners': {
      id: '/_landing/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof LandingPartnersRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/oss-friends': {
      id: '/_landing/oss-friends'
      path: '/oss-friends'
      fullPath: '/oss-friends'
      preLoaderRoute: typeof LandingOssFriendsRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/gateway': {
      id: '/_landing/gateway'
      path: '/gateway'
      fullPath: '/gateway'
      preLoaderRoute: typeof LandingGatewayRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/ecosystem': {
      id: '/_landing/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof LandingEcosystemRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/case-studies': {
      id: '/_landing/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof LandingCaseStudiesRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/federation/': {
      id: '/_landing/federation/'
      path: '/federation'
      fullPath: '/federation'
      preLoaderRoute: typeof LandingFederationIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/llms.mdx/docs/$': {
      id: '/llms.mdx/docs/$'
      path: '/llms.mdx/docs/$'
      fullPath: '/llms.mdx/docs/$'
      preLoaderRoute: typeof LlmsDotmdxDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LandingRouteChildren {
  LandingCaseStudiesRoute: typeof LandingCaseStudiesRoute
  LandingEcosystemRoute: typeof LandingEcosystemRoute
  LandingGatewayRoute: typeof LandingGatewayRoute
  LandingOssFriendsRoute: typeof LandingOssFriendsRoute
  LandingPartnersRoute: typeof LandingPartnersRoute
  LandingPricingRoute: typeof LandingPricingRoute
  LandingIndexRoute: typeof LandingIndexRoute
  LandingFederationIndexRoute: typeof LandingFederationIndexRoute
}

const LandingRouteChildren: LandingRouteChildren = {
  LandingCaseStudiesRoute: LandingCaseStudiesRoute,
  LandingEcosystemRoute: LandingEcosystemRoute,
  LandingGatewayRoute: LandingGatewayRoute,
  LandingOssFriendsRoute: LandingOssFriendsRoute,
  LandingPartnersRoute: LandingPartnersRoute,
  LandingPricingRoute: LandingPricingRoute,
  LandingIndexRoute: LandingIndexRoute,
  LandingFederationIndexRoute: LandingFederationIndexRoute,
}

const LandingRouteWithChildren =
  LandingRoute._addFileChildren(LandingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LandingRoute: LandingRouteWithChildren,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  ApiSearchRoute: ApiSearchRoute,
  DocsSplatRoute: DocsSplatRoute,
  LlmsDotmdxDocsSplatRoute: LlmsDotmdxDocsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
