name: on-mdx-change
on:
  pull_request:
    paths:
      - "packages/documentation/content/**/*.mdx"

jobs:
  validate-mdx-links:
    uses: the-guild-org/shared-config/.github/workflows/validate-mdx-links.yaml@v1
    with:
      cwd: packages/documentation
      files: content/**/*.mdx
      version: "1.1.0"
    concurrency:
      group: mdx-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
