name: on-mdx-change
on:
  pull_request:
    paths:
      - "packages/documentation/content/**/*.mdx"

jobs:
  validate-mdx-links:
    uses: the-guild-org/shared-config/.github/workflows/validate-mdx-links.yaml@v1
    with:
      node-version: "24"
      cwd: packages/documentation
      content-dir: content
      version: "1.2.1"
    concurrency:
      group: mdx-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
