name: pr
on:
  pull_request: {}

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  typescript:
    uses: ./.github/workflows/typescript-typecheck.yml

  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  e2e:
    uses: ./.github/workflows/e2e.yml
    secrets: inherit

  website-preview:
    needs: [test]
    uses: ./.github/workflows/website.yml
    with:
      environment: preview
    if: ${{ !github.event.pull_request.head.repo.fork }}
    secrets: inherit

  storybook-preview:
    uses: ./.github/workflows/storybook.yml
    with:
      environment: storybook-preview
    if: ${{ !github.event.pull_request.head.repo.fork }}
    secrets: inherit

  # todo: release snapshots of the libraries (if we need them)
  # alpha:
  #   uses: the-guild-org/shared-config/.github/workflows/release-snapshot.yml@main
  #   if: ${{ github.event.pull_request.title != 'Upcoming Release Changes' }}
  #   with:
  #     npmTag: alpha
  #     buildScript: build
  #     packageManager: bun
  #   secrets:
  #     githubToken: ${{ secrets.GITHUB_TOKEN }}
  #     npmToken: ${{ secrets.NPM_TOKEN }}
